---
- hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Install System Packages
      package:
        name:
          - python3
          - python3-pip
          - python3-setuptools
          - git
          - redis
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - virtualenv
        state: latest

    - name: Pip Instalations
      pip:
        name:
          - flask
          - redis
          - docker
          - docker-compose
          - pyyaml
          - urllib3
        executable: pip3
        state: latest

    - name: Clone user-color-page repository
      git:
        repo: 'https://github.com/Drabants/user_color_webpage.git'
        dest: /home/color
        clone: yes
        update: no

    - name: Run `docker-compose up`
      docker_compose:
        project_src: /home/color
        build: yes
      register: output
